name: pull-request-workflow
on: pull_request

jobs:
  pull-request-jobs:
  runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hihi
        echo hoho